// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Exhibit = Collections['exhibits']['schema']['_output']
export declare const exhibits: Exhibit[]
